### PR TITLE
Mark HTTP/2 connection as closing on exception caught

### LINKED ISSUE #2685: ConnectionClosedAfterIoExceptionTest failure
https://github.com/apple/servicetalk/pull/2684/checks?check_run_id=16377684587

```
ConnectionClosedAfterIoExceptionTest.test(HttpProtocol) [2]: protocol=HTTP_2

io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:650)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:953)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:933)
	at app//io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.servicetalk.transport.netty.internal.ServiceTalkWireLogger.flush(ServiceTalkWireLogger.java:188)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush0(AbstractHttp2StreamChannel.java:1132)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.flush(AbstractHttp2StreamChannel.java:1078)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	at app//io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush(AbstractHttp2StreamChannel.java:438)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.20/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
```

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

Similar to #2675, `H2ParentConnectionContext.AbstractH2ParentConnection` should mark the `Channel` as closing on `exceptionCaught`. If there is no active `Subscriber`, it should enforce channel closure using `ChannelCloseUtils`.
In case users don't have offloading, there is a risk to retry on the same IO thread. We should notify `LoadBalancer` that this connection is closing to avoid retrying on the same connection.

Modifications:

- Invoke `parentContext.notifyOnClosingImpl()` inside `exceptionCaught` before notifying `transportError` and failing subscriber;
- Close the h2 channel if there is no active `Subscriber` to consume the error;
- Remove `H2ParentConnectionContext.hasSubscriber()` that does not seem required anymore;
- Enhance `ConnectionClosedAfterIoExceptionTest` to make sure we fail only the first connect attempt, we capture `RetryableException`s, and capture the callers stack trace if `client.request(...)` fails;

Result:

Retries always select a different connection if existing connection observes an exception.
Fixes #2685.

### CODE REVIEW

**Comment by idelpivnitskiy** [comment]
CI shows that `H2PriorKnowledgeFeatureParityTest > serverGracefulClose` is failing, but I can not reproduce it locally. Will dig deeper next week.

File: servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java [hunk 1]
```diff
@@ -162,7 +166,11 @@ protected final void doCloseAsyncGracefully() {
         }, true);
     }
 
-    private void notifyOnClosingImpl() {    // For access from AbstractH2ParentConnection
+    /**
+     * This method is required to access notifyOnClosing() from AbstractH2ParentConnection, because usage of
+     * {@code parentContext.notifyOnClosing()} directly triggers {@link java.lang.IllegalAccessError}.
+     */
+    private void notifyOnClosingImpl() {
```
Comment (idelpivnitskiy) [inline servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java:173]: Removal of this method was the cause for `H2PriorKnowledgeFeatureParityTest > serverGracefulClose` failures 🤦 
I'm not sure why Intellij IDEA or javac could not catch this as a problem.

```
    java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method io.servicetalk.transport.netty.internal.NettyChannelListenableAsyncCloseable.notifyOnClosing()V from class io.servicetalk.http.netty.H2ParentConnectionContext$AbstractH2ParentConnection
    	at io.servicetalk.http.netty.H2ParentConnectionContext$AbstractH2ParentConnection.channelRead(H2ParentConnectionContext.java:291) ~[servicetalk-http-netty-0.42.39-SNAPSHOT.jar:?]
```

File: servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java [hunk 2]
```diff
@@ -238,19 +244,22 @@ public final void handlerRemoved(ChannelHandlerContext ctx) {
         private void doChannelClosed(final String method) {
             parentContext.notifyOnClosingImpl();
 
-            if (hasSubscriber()) {
-                tryFailSubscriber(StacklessClosedChannelException.newInstance(H2ParentConnectionContext.class, method));
-            }
+            tryFailSubscriber(StacklessClosedChannelException.newInstance(H2ParentConnectionContext.class, method));
```
Comment (daschl) [inline servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java:247]: since this method now returns a boolean, should the code do something with it here?

Comment (idelpivnitskiy) [reply servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java:247]: No, it's just best effort to propagate an exception. No need to close the channel bcz this event means that the channel is already closed

**Review by daschl — APPROVED** [review]
LGTM (but you may want another pair of eyes who is more familiar with the H2 intrinsic behavior)

File: servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java [hunk 3]
```diff
@@ -238,19 +244,22 @@ public final void handlerRemoved(ChannelHandlerContext ctx) {
...
         }
 
         @Override
         public final void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
+            // The parent channel will be closed in case of exception after the cause is propagated to subscriber.
+            // In case users don't have offloading, there is a risk to retry on the same IO thread.
+            // We should notify LoadBalancer that this connection is closing to avoid retrying on the same connection.
+            parentContext.notifyOnClosingImpl();
             cause = wrapIfNecessary(cause);
-            if (observer != NoopConnectionObserver.INSTANCE) {
```
Comment (Scottmitch) [inline servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java:250]: I assume this is done at a higher level now?

**Review by Scottmitch — COMMENTED** [review]
quick peek, 1 question, lgtm
