### PR TITLE
Fix flaky `ResponseCancelTest`

### LINKED ISSUE #2297: ResponseCancelTest
https://github.com/apple/servicetalk/runs/7573293427

```
io.servicetalk.transport.netty.internal.StacklessClosedChannelException
	at io.servicetalk.transport.netty.internal.DefaultNettyConnection.channelInactive(...)(Unknown Source)
```

possibly related: https://github.com/apple/servicetalk/issues/952

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

#2297 indicates that `ResponseCancelTest` sometimes fails. It happens
because we incorrectly request signals from `delayedClientTermination`
queue. After cancel we may or may not see a terminal event. In rare
cases, `StacklessClosedChannelException` is propagated to the subscriber
after cancel. The next request does not assume that there is a pending
`ClientTerminationSignal` in the queue and considers this exception as
failure for a new request.

Modifications:
- Introduce a `requestId` to associate `ClientTerminationSignal` with
a proper request;
- Discard signals for prior requests inside `resume` logic;
- Wrap `signal.err` with `AssertionError` to preserve a caller stack
trace;

Result:

Fixes #2297.

### CODE REVIEW

File: servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java [hunk 1]
```diff
@@ -312,13 +337,19 @@ void resume() {
...
-            ClientTerminationSignal signal = signals.take();
+                           int requestId,
+                           CountDownLatch latch) throws Throwable {
+            ClientTerminationSignal signal;
+            do {
+                // In case of cancel, a terminal signal may or may not arrive to the subscriber. The requestId helps
+                // to make sure we discard optional signals of all previous requests and resuming only for the current
+                // request.
+                signal = signals.take();
+            } while (signal.requestId != requestId);
```
Comment (Scottmitch) [inline servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java:349]: nit: would logging `if (signal.requestId != requestId)` provide any value here in case the test stalls?

**Review by Scottmitch — APPROVED** [review]
