### PR TITLE
Fix flaky `PrematureClosureBeforeResponsePayloadBodyTest#notAllHeadersReceived()`

### LINKED ISSUE #1224: PrematureClosureBeforeResponsePayloadBodyTest.notAllHeadersReceived test failure
https://ci.servicetalk.io/job/servicetalk-java8-prb/1724/testReport/junit/io.servicetalk.http.netty/PrematureClosureBeforeResponsePayloadBodyTest/notAllHeadersReceived/

```
io.servicetalk.http.netty.PrematureClosureBeforeResponsePayloadBodyTest.notAllHeadersReceived

Error Message
java.lang.AssertionError: unexpected exception type thrown; expected:<io.netty.handler.codec.PrematureChannelClosureException> but was:<io.servicetalk.transport.netty.internal.CloseHandler.CloseEventObservedException>
Stacktrace
java.lang.AssertionError: unexpected exception type thrown; expected:<io.netty.handler.codec.PrematureChannelClosureException> but was:<io.servicetalk.transport.netty.internal.CloseHandler.CloseEventObservedException>
	at org.junit.Assert.assertThrows(Assert.java:1020)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at io.servicetalk.http.netty.PrematureClosureBeforeResponsePayloadBodyTest.notAllHeadersReceived(PrematureClosureBeforeResponsePayloadBodyTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:171)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.servicetalk.transport.netty.internal.CloseHandler$CloseEventObservedException: CHANNEL_CLOSED_INBOUND(The transport backing this connection has been shutdown (read)) [id: 0x44c95b76, L:/127.0.0.1:58992 ! R:127.0.0.1/127.0.0.1:37889]
Caused by: io.netty.handler.codec.PrematureChannelClosureException: Connection closed before received headers
	at io.servicetalk.http.netty.HttpObjectDecoder.decodeLast(HttpObjectDecoder.java:469)
	at io.servicetalk.transport.netty.internal.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:305)
	at io.servicetalk.transport.netty.internal.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:274)
	at io.servicetalk.transport.netty.internal.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:266)
	at io.servicetalk.http.netty.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:514)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.servicetalk.transport.netty.internal.ServiceTalkWireLogger.userEventTriggered(ServiceTalkWireLogger.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.shutdownInput(AbstractEpollChannel.java:483)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:388)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

This test is affected by a race between propagating `onError` through
`DefaultNettyConnection#enrichError` and receiving FIN from the server
(`ChannelInputShutdownReadComplete`). The exception is always correct, but
it can be wrapped with `CloseEventObservedException` if the FIN reached the
client.

Modifications:

- Improve test's assertion to check the exception or its cause;

Result:

Fixes #1224.

### CODE REVIEW

File: servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java [hunk 1]
```diff
@@ -137,7 +140,12 @@ public void notAllHeadersReceived() throws Exception {
                 "Transfer-Encoding: chunked\r\n" +
                 "Connection: close\r\n");   // no final CRLF after headers
 
-        assertThrows(PrematureChannelClosureException.class, () -> connection.request(connection.get("/")));
+        Throwable t = assertThrows(Throwable.class, () -> connection.request(connection.get("/")));
```
Comment (Scottmitch) [inline servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java:143]: consider using `VerificationTestUtils.assertThrows(PrematureChannelClosureException.class, CloseEventObservedException.class, () -> ...)`. it doesn't allow for verification of the intermediate wrapper but maybe it is good enough or can be enhanced?

**Review by Scottmitch — APPROVED** [review]

**Review by tkountis — APPROVED** [review]
