### PR TITLE
Remove 1ms connect timeout in tests

### LINKED ISSUE #1363: MultiAddressUrlHttpClientTest.makeGetRequestAndValidate test failure
reproduced locally, macOS 11.2, IntelliJ.

suspected this is related to [.socketOption(CONNECT_TIMEOUT, 1)](https://github.com/apple/servicetalk/blob/main/servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java#L107)

```
java.util.concurrent.ExecutionException: io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:61967 (localAddress: null)

	at io.servicetalk.concurrent.api.SourceToFuture.reportGet(SourceToFuture.java:121)
	at io.servicetalk.concurrent.api.SourceToFuture.get(SourceToFuture.java:92)
	at io.servicetalk.concurrent.api.BlockingTestUtils.awaitIndefinitely(BlockingTestUtils.java:136)
	at io.servicetalk.concurrent.api.BlockingTestUtils.awaitIndefinitelyNonNull(BlockingTestUtils.java:152)
	at io.servicetalk.http.netty.MultiAddressUrlHttpClientTest.requestAndValidate(MultiAddressUrlHttpClientTest.java:295)
	at io.servicetalk.http.netty.MultiAddressUrlHttpClientTest.makeGetRequestAndValidate(MultiAddressUrlHttpClientTest.java:289)
	at io.servicetalk.http.netty.MultiAddressUrlHttpClientTest.multipleRequestsToMultipleServers(MultiAddressUrlHttpClientTest.java:280)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:170)
	at io.servicetalk.concurrent.internal.ServiceTalkTestTimeout$TimeoutStatement$CallableStatement.call(ServiceTalkTestTimeout.java:162)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.servicetalk.client.api.ConnectTimeoutException: Failed to connect: /127.0.0.1:61967 (localAddress: null)
	at io.servicetalk.tcp.netty.internal.TcpConnector$1.lambda$handleSubscribe$0(TcpConnector.java:112)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe$2.run(AbstractKQueueChannel.java:563)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /127.0.0.1:61967
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe$2.run(AbstractKQueueChannel.java:562)
	... 10 more
```

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Motivation:

We added `socketOption(CONNECT_TIMEOUT, 1)` in the past to make some
tests pass on Windows with a comment that Windows uses seconds for the
timeout value. However, Linux uses milliseconds and the `CONNECT_TIMEOUT`
socket option says it have to be in milliseconds. 1ms timeout makes
these tests flaky on Linux and macOS. Let's revisit when we will have
Windows CI pipeline and understand why this socket option is not consistent
on different OS.

Modifications:

- Remove `CONNECT_TIMEOUT` from `H2PriorKnowledgeFeatureParityTest`
and `MultiAddressUrlHttpClientTest`;

Result:

Fixes #1363. Tests do not fail due to 1ms connect timeout on Linux.

### CODE REVIEW

File: servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java [hunk 1]
```diff
@@ -800,7 +799,6 @@ public void serverGracefulClose() throws Exception {
         h1ServerContext.closeAsyncGracefully().subscribe();
 
         try (BlockingHttpClient client2 = forSingleAddress(HostAndPort.of(serverAddress))
-                .socketOption(CONNECT_TIMEOUT, 1) // windows default connect timeout is seconds, we want to fail fast.
```
Comment (Scottmitch) [inline servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java:803]: This test looks racy.

Test Thread:
- initiate server graceful close
- client send 2nd request
- assert client 2nd request fails (assumes server graceful close has started, but it hasn't yet)

Server IO thread (or offload thread)
- graceful close state updated (happens after the new connection / request has already started)

**Review by Scottmitch — APPROVED** [review]
